spring:
  application:
    name: ClassDesign
  datasource:
    url: jdbc:postgresql://192.168.60.133:7654/Test
    username: xlevon
    password: xlevon@123
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线命名转换